server:
  port: ${PORT:8081}


# This part will be fetched from config server from https://github.com/imdadareeph/solace-topic-queue-configs/blob/main/solace-topic-queue/dev/solace-topic-queue-dev.yml
#

#solace:
##  host: tcp://localhost:55554
##  username: admin
##  password: admin
##  vpnName: default
##  queues:
##    - name: ORDER_CREATED
##      topics:
##        - orderservice/failed/v1/created
##        - orderservice/success/v1/completed
##    - name: PAYMENT_COMPLETED
##      topics:
##        - paymentservice/success/v1/completed
##        - topic4
##    - name: CART_CREATED
##      topics:
##        - cartservice/success/v1/created