DROP TABLE IF EXISTS QUEUES cascade;
DROP TABLE IF EXISTS TOPICS cascade;


CREATE TABLE QUEUES (
	id INT PRIMARY KEY,
	QUEUE_NAME VARCHAR(100) NULL,
	QUEUE_DESCRIPTION VARCHAR(100) NULL,
	QUEUE_ENABLED BIT
);


CREATE TABLE TOPICS (
	ID INT PRIMARY KEY,
	TOPIC_TYPE VARCHAR(50) NULL,
	TOPIC_NAME VARCHAR(100) NULL,
	TOPIC_DESCRIPTION VARCHAR(100)  NULL,
	LASTUPDATE VARCHAR NULL,
	QUEUES VARCHAR NULL,
	FOREIGN KEY (QUEUES) REFERENCES QUEUES(id)
);

